In [9]:
from numpy import shape, array
# equations
# -0.2x1 + 0.1x2 + 0x3 + 0x4 + 0x5 + 400 = y1
# 0.1x1 - 0.4x2 + 0x3 + 0.1x4 + 0x5 - 100 = y2
# 0.1x1 + 0.2x2 - 0.5x3 + 0.1x4 + 0x5 - 100 = y3
# 0x1 + 0.1x2 + 0.2x3 - 0.4x4 + 0x5 = y4
# 0x1 + 0x2 + 0.3x3 + 0x4 - 0.5x5 = y5

In [10]:

A = array([[-0.2,0.1,0,0,0], [0.1,-0.4,0,0.1,0], [0.1,0.2,-0.5,0.1,0], [0,0.1,0.2,-0.4,0], [0,0,0.3,0,-0.5]])
b = array([[400],[-100],[-100],[0],[0]])
x = array([[400],[400],[400],[400],[400]])

# 1) Fill in the Matrix A and vector b
print("A (row, col):", shape(A))
print("Matrix A is below: ")
for line in A:
    print('  '.join(map(str, line)))

print("b (row, col):", shape(b))
print("Matrix b is below: ")
for line in b:
    print('  '.join(map(str, line)))

print("x (row, col):", shape(x))
print("Matrix x is below: ")
for line in x:
    print('  '.join(map(str, line)))


A (row, col): (5, 5)
Matrix A is below: 
-0.2  0.1  0.0  0.0  0.0
0.1  -0.4  0.0  0.1  0.0
0.1  0.2  -0.5  0.1  0.0
0.0  0.1  0.2  -0.4  0.0
0.0  0.0  0.3  0.0  -0.5
b (row, col): (5, 1)
Matrix b is below: 
400
-100
-100
0
0
x (row, col): (5, 1)
Matrix x is below: 
400
400
400
400
400


In [11]:
# 2)
# a) change in population for one month
print("Ax = \n", A@x)
print("y = \n", A@x+b)

# b) update the population after first month
print("delta_y = \n", A@x+b+x)


Ax = 
 [[-40.]
 [-80.]
 [-40.]
 [-40.]
 [-80.]]
y = 
 [[ 360.]
 [-180.]
 [-140.]
 [ -40.]
 [ -80.]]
delta_y = 
 [[760.]
 [220.]
 [260.]
 [360.]
 [320.]]


In [8]:
# 3) Loop to find population after 12 months
A = array([[-0.2,0.1,0,0,0], [0.1,-0.4,0,0.1,0], [0.1,0.2,-0.5,0.1,0], [0,0.1,0.2,-0.4,0], [0,0,0.3,0,-0.5]])
b = array([[400],[-100],[-100],[0],[0]])
x = array([[400],[400],[400],[400],[400]])
for i in range(12):
    print("After {} month, the population will be: ".format(i+1))
    x = A@x+b+x
    print("population = \n", x)



A = array([[-0.2,0.1,0,0,0], [0.1,-0.4,0,0.1,0], [0.1,0.2,-0.5,0.1,0], [0,0.1,0.2,-0.4,0], [0,0,0.3,0,-0.5]])
b = array([[400],[-100],[-100],[0],[0]])
x = array([[400],[400],[400],[400],[400]])
for i in range(12):
  print("After {} month, the population will be: ".format(i+1))
  x = A@x+b+x
  print("population = \n", x)



After 1 month, the population will be: 
population = 
 [[760.]
 [220.]
 [260.]
 [360.]
 [320.]]
After 2 month, the population will be: 
population = 
 [[1030.]
 [ 144.]
 [ 186.]
 [ 290.]
 [ 238.]]
After 3 month, the population will be: 
population = 
 [[1238.4]
 [ 118.4]
 [ 153.8]
 [ 225.6]
 [ 174.8]]
After 4 month, the population will be: 
population = 
 [[1402.56]
 [ 117.44]
 [ 146.98]
 [ 177.96]
 [ 133.54]]
After 5 month, the population will be: 
population = 
 [[1533.792]
 [ 128.516]
 [ 155.03 ]
 [ 147.916]
 [ 110.864]]
After 6 month, the population will be: 
population = 
 [[1639.8852]
 [ 145.2804]
 [ 171.389 ]
 [ 132.6072]
 [ 101.941 ]]
After 7 month, the population will be: 
population = 
 [[1726.4362 ]
 [ 164.41748]
 [ 191.99982]
 [ 128.37016]
 [ 102.3872 ]]
After 8 month, the population will be: 
population = 
 [[1797.590708]
 [ 184.131124]
 [ 214.364042]
 [ 131.863808]
 [ 108.793546]]
After 9 month, the population will be: 
population = 
 [[1856.4856788]
 [ 203.424126 ]
 [ 23